[package]
name = "notification-service"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.5.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.30"
prost = "0.13.1"
lettre = "0.11.7"

[build-dependencies]
prost-build = "0.13.1"
